
export const resources = {
  HEADER: {
    UPLOAD: "آپلود",
    NOTIFICATION: "اعلان ها",
    MESSAGES: "پیام ها",
    SEARCH: "جستجو..",
    SEEALL: "نمایش همه",
    ACCOUNT_SETTING: "تنظیمات حساب کاربری",
    LOGOUT: "خروج"
  },
  SIGNIN: {
    HEADING_SIGNIN: "ورود",
    INFO_SIGNIN: "ورود به حساب کاربری با ایمیل",
    INPUT_PLACEHOLDER_EMAIL: "example@mydomain.com",
    INPUT_PLACEHOLDER_PASS: "***********",
    FORGETpASSWORD_TAG: "کلمه عبور را فراموش کرده ام",
    NOT_REGISTERD: "هنوز ثبت نام نکردی؟",
    CREATE_ACCOUNT: "ایجاد یک حساب کاربری",
    BUTTON_TEXT: "ورود",
    INPUT_REQUIRED_EMAIL: "اجباری می باشد",
    INPUT_REQUIRED_PASSWORD: "اجباری می باشد",
    INPUT_MAX_EMAIL: "حداگثر تعداد کاراکتر 255 می باشد",
    INPUT_MAX_PASSWORD: "حداکثر تعداد کاراکنر 32 می باشد",
    INPUT_MIN_EMAIL: "حداقل تعداد کاراکتر 5 می باشد",
    INPUT_MIN_PASSWORD:  "حداقل تعداد کاراکتر 5 می باشد",
    SUCCESS_SIGNIN:"ورود با موفقیت انجام شد",
    ERROR_SIGNIN:"ایمیل یا کلمه عبور نادرست می باشد"
  },
  SIGNUP:{
    HEADING_SIGNUP: "ثبت نام",
    INFO_SIGNUP: "برای مدیریت حساب کاربری ثبت نام کنید",
    INPUT_FIRSTNAME: "نام",
    INPUT_LASTNAME: "نام خانوادگی",
    INPUT_PASSWORD: "کلمه عبور",
    INPUT_CONFIRMPASSWORD: "تکرار کلمه عبور",
    INPUT_EMAIL: "ایمیل",
    I_AGREE:" موافقم ",
    TERMS_AND_CONDITIONS:"قوانین و مقررات",
    HAS_ACCOUNT:"یک حساب کاربری داری؟",
    SIGNIN_ACCOUNT:"ورود به حساب کاربری",
    BUTTON_TEXT: "ثبت نام",
    INPUT_REQUIRED: "اجباری می باشد",
    INPUT_MAX_EMAIL: "حداگثر تعداد کاراکتر 255 می باشد",
    INPUT_MAX_PASSWORD: "حداکثر تعداد کاراکنر 32 می باشد",
    INPUT_MAX_FIRSTNAME: "حداگثر تعداد کاراکتر 50 می باشد",
    INPUT_MAX_LASTNAME: "حداگثر تعداد کاراکتر 50 می باشد",
    INPUT_MIN_PASSWORD:  "حداقل تعداد کاراکتر 5 می باشد",
    INPUT_MIN_EMAIL: "حداقل تعداد کاراکتر 5 می باشد",
    INPUT_MIN_FIRSTNAME: "حداقل تعداد کاراکتر 3 می باشد",
    INPUT_MIN_LASTNAME: "حداقل تعداد کاراکتر 3 می باشد",
    INPUT_MATCH_CONFIRMPASSWORD: "با کلمه عبور شما مطابق نمی باشد",
    SUCCESS_SIGNUP:"ثبت نام با موفقیت انجام شد",
    ERROR_SIGNUP:"ثبت نام با خطا مواجه شد"
  },
  SIDEBAR: {
    POST: "پست",
    FOLLOWING: "هواداران",
    FOLLOWERS: "دوستان",
    FEED: "خانه",
    EXPLORE: "بازدید",
    MESSAGES: "پیام ها",
    TRENDING: "علاقه مندی ها",
    SETTING: "تنظیمات",
    PROFILE: "پروفایل",
    LOGOUT: "خروج",
    SWITCHTONIGHTMOODE: "تغییر حالت شب"
  },
  INITlAYOUT: {
    BUTTON_SIGNIN: " ورود ",
    BUTTON_SIGNUP: " ثبت نام ",
    HELP: " راهنما ",
    TERMS: " قوانین ",
    ABOUT: " درباره ما ",
    DEVELOP: " طراحی و توسعه ",
    INSTELLLO: " اینستلو ",
    PRIVACY:" حریم خصوصی "
  }
}